name: Java CI with Maven
on:
  workflow_dispatch:
    inputs:
      remoteCall:
        description: 'run test manual'
        required: false
        default: 'web'
        type: string
env:
  firstname: 'sam'
  website: 'https://int-2.bmw.co.za'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      max-parallel: 1
      matrix:
        run: [ 'list order related', 'configure printer', 'manage label' ]
        os: [ ubuntu-latest ]

    steps:
      - name: Code Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        continue-on-error: true
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Run List Order Test
        run: |
          echo '[${{matrix.run}} == 'list order related']'

      - name: Run Printer Test
        run: |
          echo '[${{matrix.run}} == 'configure printer']'

      - name: Run List Manage Label Test
        run: |
          echo '[${{matrix.run}} == 'manage label']'

      - name: Build with Maven
        run: |
          echo ${{ inputs.remoteCall }}
          echo ${{ github.event.inputs.remoteCall }}
          echo ${{ job.status }}
          echo ${{ job.services }}
          echo ${{ github.action }}
          echo ${{ github.action_status }}
          echo ${{ env.website }}

  random-job:
    needs:
      - build
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        os: [ ubuntu-latest ]
        node-version: [ 8 ]
    steps:
      - name: Generate numbers
        id: generate_number
        run: |
          echo "random_number=$(($RANDOM % 2))" >> GITHUB_OUTPUT
          echo "Hi ${{ env.website }}"
          echo ${{ runner.os }}
          echo ${{ secrets.PASSCODE }}

  call-reusable-workflow:
    uses: ./.github/workflows/reusable-workflow.yml
    with:
      node-version: 8