name: Java CI with Maven

on:
  workflow_dispatch:
    inputs:
      remoteCall:
        description: 'run test manual'
        required: false
        default: 'web'
        type: string
env:
  firstname: 'sam'
  website: 'https://int-2.bmw.co.za'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      max-parallel: 2
      matrix:
        os: [ ubuntu-latest ]

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        continue-on-error: true
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run: |
          mvn -B package --file pom.xml
          echo ${{ inputs.remoteCall }}
          echo ${{ github.event.inputs.remoteCall }}
          echo ${{ job.status }}
          echo ${{ job.services }}
          echo ${{ github.action }}
          echo ${{ github.action_status }}
          echo ${{ env.website }}

      - name: Update dependency graph
        uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6
        continue-on-error: true


  random-job:
    needs:
      - build
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        os: [ ubuntu-latest ]
    steps:
      - name: Generate numbers
        id: generate_number
        run: |
          echo "random_number=$(($RANDOM % 2))" >> GITHUB_OUTPUT
          echo "Hi ${{ env.website }}"
          echo ${{ runner.os }}
          echo ${{ secrets.PASSCODE}}