name: Greetings

on:
  workflow_dispatch:
    inputs:
      name:
        description: 'some thing greater than'
        default: true
        required: true
        type: boolean
env:
  filepath: ''
jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - name: Interactions with User
        uses: actions/first-interaction@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          issue-message: "Message that will be displayed on users' first issue"
          pr-message: "Message that will be displayed on users' first pull request"

      - run: |
          echo "Hello, ${{ github.actor }}"