name: Reusable Workflow
on:
  workflow_call:
    inputs:
      node-version:
        required: true
        type: string
jobs:
  reuse-me:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        os: [ ubuntu-latest ]
    steps:
      - uses: actions/checkout@v4
      - name: Output Node Information
        run: |
          echo 'This is version: ${{ inputs.node-version }}'