on:
  workflow_dispatch:
    - cron: '* * * * *'
jobs:
  set-1:
    strategy:
      matrix:
        prod: [ set-1, set-2, set-3, set-4, set-5 ]
        level: [ dev, staging, production ]
    uses: ./.github/workflows/reusable-workflow.yml
    secrets: inherit
    with:
      node-version: 8

