name: Rough Worker
on:
  workflow_dispatch:

jobs:
  set-build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        prod: [ test-set-1, test-set-2, test-set-3 ]
        level: [ int-1, int-2, pre-prod ]
        os: [ ubuntu-latest ]
        node-version: [ 8 ]
    steps:
      - name: Run Test
        run: |
          echo 'This is version: ${{ matrix.node-version }}'